import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from './Components/navbar/navbar'
import Hero from '@/home'
import Feature from './Components/feature/feature'
import WorkFlow from './Components/Work/work'
import Footer from './Components/footer/footer'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Help Me out</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
    <NavBar />
<Hero/>
<Feature/>
<WorkFlow/>

<Footer/>
      </main>
    </>
  )
}